### ISSUE TITLE
Acceptance fails for 1e5 keys

### ISSUE THREAD

**Issue by lekoder** [lekoder/consul-to-json#6]
Acceptance tests fail when trying to restore large JSON file with 100000 keys:

```
Unhandled rejection Error: connect EADDRNOTAVAIL 127.0.0.1:8500 - Local (127.0.0.1:0)
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at connect (net.js:875:16)
    at net.js:964:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

This could be connected with #3

**Comment by lekoder** [comment]
This was caused by opening excessive numer of TCP connections to consul and exhausting all available local ports. Implemented concurrency limit to eliminate.
